### ISSUE TITLE
fix parenthesis in jsdoc @type

### ISSUE THREAD

**Issue by wommy** [BenDMyers/serverless-contrast-starter#1]
https://github.com/BenDMyers/serverless-contrast-starter/blob/74003a3c8f0bec7893ab5f44f3cb9e5c939f5bcb/.eleventy.js#L4

seems like theres one too many closing parentheses before the arrow? 
`EleventyConfig)) => EleventyReturnValue`

i dont know much about TS so imma just stay outta this one

**Comment by wommy** [comment]
of course i find the documentation one minute after i post

https://github.com/11ty/eleventy/discussions/2089#discussioncomment-1647706

im still leaning towards it being a typo

**Comment by BenDMyers** [comment]
Good catch - thank you @wommy! Fixed in c5644182a0fb1898e55c456e37a8fe8d4afc04b0

**Comment by wommy** [comment]
he even added a [shorter version!](https://github.com/11ty/eleventy/discussions/2089#discussion-3686674)

[still waiting to hear back if its rock-solid](https://github.com/11ty/eleventy/discussions/2089#discussioncomment-2291556)
